# -*- coding: utf-8 -*-
"""dowload-youtube-video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McfikAiiFUw-pIuOzte0OOJ-Pr89ukfb
"""

#Download video from YouTube
import pytube
from pytube import YouTube
import os
def downloadYouTube(videourl, path):
    yt = YouTube(videourl)
    yt = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
    if not os.path.exists(path):
        os.makedirs(path)
        yt.download(path)
downloadYouTube('https://youtu.be/Gr0HpDM8Ki8?list=PLcQZGj9lFR7y5WikozDSrdk6UCtAnM9mB', './car-videos')